[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tsrc/linker.ld",
]

[target.loongarch64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tsrc/linker-la64.ld",
]
